<a href="https://colab.research.google.com/github/saromaddy/numpy_pandas/blob/main/Numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numerical python - NumPY

#Always the data will be in array
#Array --> all the data in the list have similar dataset


In [1]:
import numpy as np

In [2]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [4]:
x = np.zeros(5) #it will create zeros in one dimensional array
x

array([0., 0., 0., 0., 0.])

In [5]:
x[2]=23

In [6]:
x

array([ 0.,  0., 23.,  0.,  0.])

In [ ]:
x[0]= 'good' #numpy doesn't allow multiple data type since it is an array

ValueError: could not convert string to float: 'good'

In [ ]:
x = [5,10,15,20,25] #adding all the elements in that array
np.sum(x)

75

In [ ]:
np.mean(x) #Average

15.0

In [ ]:
x = np.zeros(12)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
x = np.arange(5,101,5) #from 5 to 100 with the step up of 5 it will print the numbers
x

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [ ]:
x = np.arange(1,13)
x


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
y = x.reshape(3,4) #reshape the one dimensional array to two dimentsional number of elements = row X column
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
y[1][2] #fetching element through indexing

7

In [ ]:
x = np.arange(1,13).reshape(3,4) #creating two dimensional array using arange and reshape
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
x = np.arange(1,61).reshape(3,4,5) # for creating 3 dimensional matrix
x


array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])

In [ ]:
x = np.arange(1,121).reshape(2,3,4,5)# for creating the 4 dimension
x

array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])

In [ ]:
x[1][0][1][2]

68

In [ ]:
x = np.random.random(6) * -500
x

array([-358.01477292,  -78.86631834, -108.39669716, -341.50071959,
       -226.19037012, -125.01975157])

In [ ]:
x = 20 + 60 * np.random.random(10)

x



array([71.93167691, 55.63469514, 65.94855256, 58.51548992, 35.96343594,
       22.38760147, 46.35301034, 54.25275084, 61.08975427, 42.49528579])

In [ ]:
x = np.random.arange(1,301)

AttributeError: module 'numpy.random' has no attribute 'arange'

In [ ]:
x = np.random.randint(15) #creating random integer

x # by default this will generate from 0 to 15 integer

9

In [ ]:
x = np.random.randint(5,50, size = 10) #both ends included

In [ ]:
x

array([35, 37,  5, 20, 39, 48, 17, 21, 15, 42])

In [ ]:
x = np.random.randint(-500,500, size = 1000)

In [ ]:
x

array([ 459,  -66, -489, -418,  -17, -429,  282,  444,   97,   98, -282,
       -472, -417,  145, -109,   48,  422,  361,  153,   64,  -53,  109,
         38,   56, -431,  -67,  205,  323,  226, -407, -192, -420, -332,
       -134,  182,  359, -308,  231, -348,  267,  334,  -36,  246,  174,
        277,  -26,   83,  292,   52, -174,  323,  402,  474,  464,  238,
        123,  374,  207,  438, -454, -310,   85, -421, -147,  145, -267,
       -312, -472, -460, -455, -311,  456,  481, -364,  272, -324, -497,
        194, -238, -371, -407,  484, -290,  393,  308,  389, -334,  188,
        230, -300,  130, -229, -365, -240,  157,  322,  336, -356,  -83,
        -85,   12,  367, -167, -127, -144, -464, -316,   89,  236,  456,
       -259,  147,  126,  450, -303,  266, -147,   16, -461, -241, -494,
        355, -429,  104,  458,   15,  399,   80,   55,  -36, -117, -217,
          7, -382, -404, -420, -157, -292,  169, -265,  283, -224, -313,
        226,  352,  -54, -287,  -23, -380,  -76,  3

In [ ]:
# Data Distribution

x=np.random.choice(["josh","jansi","saravana","tamil","hari"],size=542)
x

array(['josh', 'hari', 'saravana', 'saravana', 'jansi', 'hari', 'hari',
       'tamil', 'jansi', 'hari', 'hari', 'saravana', 'hari', 'hari',
       'tamil', 'hari', 'jansi', 'hari', 'josh', 'jansi', 'jansi',
       'tamil', 'saravana', 'hari', 'tamil', 'hari', 'tamil', 'tamil',
       'tamil', 'josh', 'jansi', 'saravana', 'tamil', 'jansi', 'saravana',
       'saravana', 'josh', 'josh', 'jansi', 'saravana', 'saravana',
       'saravana', 'hari', 'jansi', 'jansi', 'hari', 'tamil', 'josh',
       'josh', 'josh', 'saravana', 'josh', 'hari', 'hari', 'tamil',
       'saravana', 'jansi', 'hari', 'jansi', 'josh', 'jansi', 'jansi',
       'tamil', 'josh', 'josh', 'jansi', 'josh', 'saravana', 'hari',
       'tamil', 'tamil', 'tamil', 'saravana', 'hari', 'tamil', 'jansi',
       'jansi', 'jansi', 'saravana', 'jansi', 'jansi', 'hari', 'jansi',
       'hari', 'hari', 'jansi', 'jansi', 'jansi', 'tamil', 'jansi',
       'jansi', 'jansi', 'josh', 'josh', 'jansi', 'josh', 'saravana',
       'hari', 'ha

In [ ]:
x=np.random.choice(["josh","jansi","saravana","tamil","hari"],size=100,p=[0.5,0.05,0.2,0.1,0.15]) #probabilities should sum to 1
x

array(['tamil', 'josh', 'josh', 'josh', 'tamil', 'josh', 'saravana',
       'josh', 'josh', 'hari', 'josh', 'josh', 'josh', 'josh', 'josh',
       'josh', 'josh', 'josh', 'josh', 'jansi', 'hari', 'saravana',
       'josh', 'josh', 'hari', 'hari', 'josh', 'josh', 'saravana', 'josh',
       'josh', 'saravana', 'hari', 'hari', 'josh', 'josh', 'josh',
       'tamil', 'josh', 'hari', 'saravana', 'josh', 'josh', 'josh',
       'josh', 'josh', 'jansi', 'saravana', 'hari', 'saravana',
       'saravana', 'josh', 'hari', 'josh', 'saravana', 'josh', 'josh',
       'josh', 'josh', 'jansi', 'tamil', 'saravana', 'jansi', 'saravana',
       'saravana', 'josh', 'saravana', 'josh', 'josh', 'josh', 'josh',
       'hari', 'josh', 'saravana', 'josh', 'josh', 'josh', 'josh',
       'jansi', 'jansi', 'jansi', 'josh', 'josh', 'josh', 'josh',
       'saravana', 'josh', 'tamil', 'josh', 'saravana', 'josh', 'jansi',
       'hari', 'josh', 'saravana', 'saravana', 'josh', 'josh', 'saravana',
       'saravana'], d

In [ ]:
x=np.random.choice(["josh","jansi","saravana","tamil","hari"],size=7000,p=[0.5,0.05,0.2,0.1,0.15])
x

array(['josh', 'tamil', 'hari', ..., 'saravana', 'josh', 'josh'],
      dtype='<U8')

In [ ]:
x=np.arange(1,500)

In [ ]:
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [ ]:
y = np.array_split(x,5)
y

[array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100]),
 array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
        127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
        166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 1

In [ ]:
x = np.linspace(2,35,10)
x

array([ 2.        ,  5.66666667,  9.33333333, 13.        , 16.66666667,
       20.33333333, 24.        , 27.66666667, 31.33333333, 35.        ])

In [ ]:
auth = {
  "apikey": "795759a5-f664-47be-aaf6-851c6b6ddcff",
  "id": "b4438580-d28e-457c-886b-3c2419ab5de2"
}

In [ ]:
url = "https://api.cricapi.com/v1/match_scorecard"

In [ ]:
import requests

In [ ]:
result = requests.get(url,params=auth)
result.json().keys()

dict_keys(['apikey', 'data', 'status', 'info'])

In [ ]:
score_card = result.json()['data']['scorecard']

{'batting': [{'batsman': {'id': 'a254feed-0d7c-4f04-a2ab-7bf9ceef156b',
    'name': 'Yashasvi Jaiswal'},
   'dismissal': 'catch',
   'bowler': {'id': '3a93bfb5-1fd1-4342-99f1-397161de9d10',
    'name': 'Sikandar Raza'},
   'catcher': {'id': '55e1ded0-dbd4-48d2-9df8-f7b92fcd0fef',
    'name': 'Brian Bennett '},
   'dismissal-text': 'c brian bennett b raza',
   'r': 36,
   'b': 27,
   '4s': 4,
   '6s': 2,
   'sr': 133.33,
   '': 0},
  {'batsman': {'id': '7263e990-a9e9-4829-8adf-760d18d1315c',
    'name': 'Shubman Gill'},
   'dismissal': 'catch',
   'bowler': {'id': '50e38c9d-bf39-44b8-b5e6-0c9f36b8cbdf',
    'name': 'Blessing Muzarabani'},
   'catcher': {'id': '3a93bfb5-1fd1-4342-99f1-397161de9d10',
    'name': 'Sikandar Raza'},
   'dismissal-text': 'c raza b muzarabani',
   'r': 66,
   'b': 49,
   '4s': 7,
   '6s': 3,
   'sr': 134.69,
   '': 0},
  {'batsman': {'id': '83fe6ab6-d63c-420e-9416-a93d59a9a964',
    'name': 'Abhishek Sharma'},
   'dismissal': 'catch',
   'bowler': {'id': '3a93

In [ ]:
data=[]
for i in score_card:
  battingdata=i["batting"]
  for j in battingdata:
    data.append(j)

In [ ]:
import pandas as pd


In [ ]:
df = pd.DataFrame(data)
df

batsman dismissal  \
0   {'id': 'a254feed-0d7c-4f04-a2ab-7bf9ceef156b',...     catch   
1   {'id': '7263e990-a9e9-4829-8adf-760d18d1315c',...     catch   
2   {'id': '83fe6ab6-d63c-420e-9416-a93d59a9a964',...     catch   
3   {'id': '50b70c71-1535-41c0-87fd-c12883105ede',...     catch   
4   {'id': '35ed1b20-38f3-4013-be2e-dc28ffbecfd6',...       NaN   
5   {'id': '11864f31-b766-4766-9cbc-5026015ace48',...       NaN   
6   {'id': '78b833a2-6813-4529-bf41-21313ebaa4e6',...     catch   
7   {'id': 'fc4102d8-b2f6-45f1-9e75-b883838f5bb1',...     catch   
8   {'id': '55e1ded0-dbd4-48d2-9df8-f7b92fcd0fef',...     catch   
9   {'id': '79eee646-64b8-4392-9ad1-cb1c7630034d',...       NaN   
10  {'id': '3a93bfb5-1fd1-4342-99f1-397161de9d10',...     catch   
11  {'id': '79adea1e-ac28-43d7-a734-b05344779200',...     catch   
12  {'id': '0528d8b0-a6ce-498f-a573-d0edb1efcf9b',...     catch   
13  {'id': '397bf103-6977-4e5b-b437-6f448764b36a',...       NaN   

                                               bowler  \
0   {'id': '3a93bfb5-1fd1-4342-99f1-397161de9d10',...   
1   {'id': '50e38c9d-bf39-44b8-b5e6-0c9f36b8cbdf',...   
2   {'id': '3a93bfb5-1fd1-4342-99f1-397161de9d10',...   
3   {'id': '50e38c9d-bf39-44b8-b5e6-0c9f36b8cbdf',...   
4                                                 NaN   
5                                                 NaN   
6   {'id': '332200ad-d1f8-4035-95c5-b33bd1c9a939',...   
7   {'id': '8df6183b-1c95-46d2-85c0-e185792d03f1',...   
8   {'id': '332200ad-d1f8-4035-95c5-b33bd1c9a939',...   
9                                                 NaN   
10  {'id': '309d3ffd-3d06-460d-9427-c559a604d471',...   
11  {'id': '309d3ffd-3d06-460d-9427-c559a604d471',...   
12  {'id': '309d3ffd-3d06-460d-9427-c559a604d471',...   
13                                                NaN   

                                              catcher  \
0   {'id': '55e1ded0-dbd4-48d2-9df8-f7b92fcd0fef',...   
1   {'id': '3a93bfb5-1fd1-4342-99f1-397161de9d10',...   
2   {'id': 'fc4102d8-b2f6-45f1-9e75-b883838f5bb1',...   
3   {'id': '78b833a2-6813-4529-bf41-21313ebaa4e6',...   
4                                                 NaN   
5                                                 NaN   
6   {'id': '83fe6ab6-d63c-420e-9416-a93d59a9a964',...   
7   {'id': '22ee45d8-0538-4e3e-a758-c515f9b86d11',...   
8   {'id': '9a71201c-c377-45aa-a355-1af6d2c4bae3',...   
9                                                 NaN   
10  {'id': '11864f31-b766-4766-9cbc-5026015ace48',...   
11  {'id': 'b51bb4e5-acdf-423b-abb3-7a1e6694d2c2',...   
12  {'id': '11864f31-b766-4766-9cbc-5026015ace48',...   
13                                                NaN   

                       dismissal-text   r   b  4s  6s      sr     
0              c brian bennett b raza  36  27   4   2  133.33  0  
1                 c raza b muzarabani  66  49   7   3  134.69  0  
2                 c t marumani b raza  10   9   1   0  111.11  0  
3            c madhevere b muzarabani  49  28   4   3  175.00  0  
4                             not out  12   7   2   0  171.43  0  
5                             not out   1   1   0   0  100.00  0  
6      c abhishek sharma b avesh khan   1   2   0   0   50.00  0  
7       c shivam dube b khaleel ahmed  13  10   3   0  130.00  0  
8         c ravi bishnoi b avesh khan   4   5   1   0   80.00  0  
9                             not out  65  49   7   1  132.65  0  
10  c rinku singh b washington sundar  15  16   3   0   93.75  0  
11  c riyan parag b washington sundar   1   2   0   0   50.00  0  
12  c rinku singh b washington sundar  37  26   2   2  142.31  0  
13                            not out  18  10   1   1  180.00  0

In [ ]:
df.iloc[0,0]

{'id': 'a254feed-0d7c-4f04-a2ab-7bf9ceef156b', 'name': 'Yashasvi Jaiswal'}