<a href="https://colab.research.google.com/github/saromaddy/numpy_pandas/blob/main/Numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numerical python - NumPY

#Always the data will be in array
#Array --> all the data in the list have similar dataset


In [1]:
import numpy as np

In [2]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [4]:
x = np.zeros(5) #it will create zeros in one dimensional array
x

array([0., 0., 0., 0., 0.])

In [5]:
x[2]=23

In [6]:
x

array([ 0.,  0., 23.,  0.,  0.])

In [ ]:
x[0]= 'good' #numpy doesn't allow multiple data type since it is an array

ValueError: could not convert string to float: 'good'

In [ ]:
x = [5,10,15,20,25] #adding all the elements in that array
np.sum(x)

75

In [ ]:
np.mean(x) #Average

15.0

In [ ]:
x = np.zeros(12)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
x = np.arange(5,101,5) #from 5 to 100 with the step up of 5 it will print the numbers
x

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [ ]:
x = np.arange(1,13)
x


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
y = x.reshape(3,4) #reshape the one dimensional array to two dimentsional number of elements = row X column
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
y[1][2] #fetching element through indexing

7

In [ ]:
x = np.arange(1,13).reshape(3,4) #creating two dimensional array using arange and reshape
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
x = np.arange(1,61).reshape(3,4,5) # for creating 3 dimensional matrix
x


array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])

In [ ]:
x = np.arange(1,121).reshape(2,3,4,5)# for creating the 4 dimension
x

array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])

In [ ]:
x[1][0][1][2]

68

In [ ]:
x = np.random.random(6) * -500
x

array([-358.01477292,  -78.86631834, -108.39669716, -341.50071959,
       -226.19037012, -125.01975157])

In [ ]:
x = 20 + 60 * np.random.random(10)

x



array([71.93167691, 55.63469514, 65.94855256, 58.51548992, 35.96343594,
       22.38760147, 46.35301034, 54.25275084, 61.08975427, 42.49528579])

In [ ]:
x = np.random.arange(1,301)

AttributeError: module 'numpy.random' has no attribute 'arange'

In [ ]:
x = np.random.randint(15) #creating random integer

x # by default this will generate from 0 to 15 integer

9

In [ ]:
x = np.random.randint(5,50, size = 10) #both ends included

In [ ]:
x

array([35, 37,  5, 20, 39, 48, 17, 21, 15, 42])

In [ ]:
x = np.random.randint(-500,500, size = 1000)

In [ ]:
x

array([ 459,  -66, -489, -418,  -17, -429,  282,  444,   97,   98, -282,
       -472, -417,  145, -109,   48,  422,  361,  153,   64,  -53,  109,
         38,   56, -431,  -67,  205,  323,  226, -407, -192, -420, -332,
       -134,  182,  359, -308,  231, -348,  267,  334,  -36,  246,  174,
        277,  -26,   83,  292,   52, -174,  323,  402,  474,  464,  238,
        123,  374,  207,  438, -454, -310,   85, -421, -147,  145, -267,
       -312, -472, -460, -455, -311,  456,  481, -364,  272, -324, -497,
        194, -238, -371, -407,  484, -290,  393,  308,  389, -334,  188,
        230, -300,  130, -229, -365, -240,  157,  322,  336, -356,  -83,
        -85,   12,  367, -167, -127, -144, -464, -316,   89,  236,  456,
       -259,  147,  126,  450, -303,  266, -147,   16, -461, -241, -494,
        355, -429,  104,  458,   15,  399,   80,   55,  -36, -117, -217,
          7, -382, -404, -420, -157, -292,  169, -265,  283, -224, -313,
        226,  352,  -54, -287,  -23, -380,  -76,  3

In [ ]:
# Data Distribution

x=np.random.choice(["josh","jansi","saravana","tamil","hari"],size=542)
x

array(['josh', 'hari', 'saravana', 'saravana', 'jansi', 'hari', 'hari',
       'tamil', 'jansi', 'hari', 'hari', 'saravana', 'hari', 'hari',
       'tamil', 'hari', 'jansi', 'hari', 'josh', 'jansi', 'jansi',
       'tamil', 'saravana', 'hari', 'tamil', 'hari', 'tamil', 'tamil',
       'tamil', 'josh', 'jansi', 'saravana', 'tamil', 'jansi', 'saravana',
       'saravana', 'josh', 'josh', 'jansi', 'saravana', 'saravana',
       'saravana', 'hari', 'jansi', 'jansi', 'hari', 'tamil', 'josh',
       'josh', 'josh', 'saravana', 'josh', 'hari', 'hari', 'tamil',
       'saravana', 'jansi', 'hari', 'jansi', 'josh', 'jansi', 'jansi',
       'tamil', 'josh', 'josh', 'jansi', 'josh', 'saravana', 'hari',
       'tamil', 'tamil', 'tamil', 'saravana', 'hari', 'tamil', 'jansi',
       'jansi', 'jansi', 'saravana', 'jansi', 'jansi', 'hari', 'jansi',
       'hari', 'hari', 'jansi', 'jansi', 'jansi', 'tamil', 'jansi',
       'jansi', 'jansi', 'josh', 'josh', 'jansi', 'josh', 'saravana',
       'hari', 'ha

In [ ]:
x=np.random.choice(["josh","jansi","saravana","tamil","hari"],size=100,p=[0.5,0.05,0.2,0.1,0.15]) #probabilities should sum to 1
x

array(['tamil', 'josh', 'josh', 'josh', 'tamil', 'josh', 'saravana',
       'josh', 'josh', 'hari', 'josh', 'josh', 'josh', 'josh', 'josh',
       'josh', 'josh', 'josh', 'josh', 'jansi', 'hari', 'saravana',
       'josh', 'josh', 'hari', 'hari', 'josh', 'josh', 'saravana', 'josh',
       'josh', 'saravana', 'hari', 'hari', 'josh', 'josh', 'josh',
       'tamil', 'josh', 'hari', 'saravana', 'josh', 'josh', 'josh',
       'josh', 'josh', 'jansi', 'saravana', 'hari', 'saravana',
       'saravana', 'josh', 'hari', 'josh', 'saravana', 'josh', 'josh',
       'josh', 'josh', 'jansi', 'tamil', 'saravana', 'jansi', 'saravana',
       'saravana', 'josh', 'saravana', 'josh', 'josh', 'josh', 'josh',
       'hari', 'josh', 'saravana', 'josh', 'josh', 'josh', 'josh',
       'jansi', 'jansi', 'jansi', 'josh', 'josh', 'josh', 'josh',
       'saravana', 'josh', 'tamil', 'josh', 'saravana', 'josh', 'jansi',
       'hari', 'josh', 'saravana', 'saravana', 'josh', 'josh', 'saravana',
       'saravana'], d

In [ ]:
x=np.random.choice(["josh","jansi","saravana","tamil","hari"],size=7000,p=[0.5,0.05,0.2,0.1,0.15])
x

array(['josh', 'tamil', 'hari', ..., 'saravana', 'josh', 'josh'],
      dtype='<U8')

In [ ]:
x=np.arange(1,500)

In [ ]:
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [ ]:
y = np.array_split(x,5)
y

[array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100]),
 array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
        127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
        166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 1

In [ ]:
x = np.linspace(2,35,10)
x

array([ 2.        ,  5.66666667,  9.33333333, 13.        , 16.66666667,
       20.33333333, 24.        , 27.66666667, 31.33333333, 35.        ])

In [7]:
auth = { # this the api that we received from cricket api
  "apikey": "795759a5-f664-47be-aaf6-851c6b6ddcff",
  "id": "b4438580-d28e-457c-886b-3c2419ab5de2"
}

In [8]:
url = "https://api.cricapi.com/v1/match_scorecard"

In [9]:
import requests

/Users/saro/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [10]:
result = requests.get(url,params=auth)
result.json().keys()

dict_keys(['apikey', 'data', 'status', 'info'])

In [11]:
score_card = result.json()['data']['scorecard']

{'batting': [{'batsman': {'id': 'a254feed-0d7c-4f04-a2ab-7bf9ceef156b',
    'name': 'Yashasvi Jaiswal'},
   'dismissal': 'catch',
   'bowler': {'id': '3a93bfb5-1fd1-4342-99f1-397161de9d10',
    'name': 'Sikandar Raza'},
   'catcher': {'id': '55e1ded0-dbd4-48d2-9df8-f7b92fcd0fef',
    'name': 'Brian Bennett '},
   'dismissal-text': 'c brian bennett b raza',
   'r': 36,
   'b': 27,
   '4s': 4,
   '6s': 2,
   'sr': 133.33,
   '': 0},
  {'batsman': {'id': '7263e990-a9e9-4829-8adf-760d18d1315c',
    'name': 'Shubman Gill'},
   'dismissal': 'catch',
   'bowler': {'id': '50e38c9d-bf39-44b8-b5e6-0c9f36b8cbdf',
    'name': 'Blessing Muzarabani'},
   'catcher': {'id': '3a93bfb5-1fd1-4342-99f1-397161de9d10',
    'name': 'Sikandar Raza'},
   'dismissal-text': 'c raza b muzarabani',
   'r': 66,
   'b': 49,
   '4s': 7,
   '6s': 3,
   'sr': 134.69,
   '': 0},
  {'batsman': {'id': '83fe6ab6-d63c-420e-9416-a93d59a9a964',
    'name': 'Abhishek Sharma'},
   'dismissal': 'catch',
   'bowler': {'id': '3a93

In [12]:
data=[]
for i in score_card:
  battingdata=i["batting"]
  for j in battingdata:
    data.append(j)

In [13]:
import pandas as pd


In [22]:
df = pd.DataFrame(data)
df

batsman dismissal  \
0   {'id': 'a254feed-0d7c-4f04-a2ab-7bf9ceef156b',...     catch   
1   {'id': '7263e990-a9e9-4829-8adf-760d18d1315c',...     catch   
2   {'id': '83fe6ab6-d63c-420e-9416-a93d59a9a964',...     catch   
3   {'id': '50b70c71-1535-41c0-87fd-c12883105ede',...     catch   
4   {'id': '35ed1b20-38f3-4013-be2e-dc28ffbecfd6',...       NaN   
5   {'id': '11864f31-b766-4766-9cbc-5026015ace48',...       NaN   
6   {'id': '78b833a2-6813-4529-bf41-21313ebaa4e6',...     catch   
7   {'id': 'fc4102d8-b2f6-45f1-9e75-b883838f5bb1',...     catch   
8   {'id': '55e1ded0-dbd4-48d2-9df8-f7b92fcd0fef',...     catch   
9   {'id': '79eee646-64b8-4392-9ad1-cb1c7630034d',...       NaN   
10  {'id': '3a93bfb5-1fd1-4342-99f1-397161de9d10',...     catch   
11  {'id': '79adea1e-ac28-43d7-a734-b05344779200',...     catch   
12  {'id': '0528d8b0-a6ce-498f-a573-d0edb1efcf9b',...     catch   
13  {'id': '397bf103-6977-4e5b-b437-6f448764b36a',...       NaN   

                                               bowler  \
0   {'id': '3a93bfb5-1fd1-4342-99f1-397161de9d10',...   
1   {'id': '50e38c9d-bf39-44b8-b5e6-0c9f36b8cbdf',...   
2   {'id': '3a93bfb5-1fd1-4342-99f1-397161de9d10',...   
3   {'id': '50e38c9d-bf39-44b8-b5e6-0c9f36b8cbdf',...   
4                                                 NaN   
5                                                 NaN   
6   {'id': '332200ad-d1f8-4035-95c5-b33bd1c9a939',...   
7   {'id': '8df6183b-1c95-46d2-85c0-e185792d03f1',...   
8   {'id': '332200ad-d1f8-4035-95c5-b33bd1c9a939',...   
9                                                 NaN   
10  {'id': '309d3ffd-3d06-460d-9427-c559a604d471',...   
11  {'id': '309d3ffd-3d06-460d-9427-c559a604d471',...   
12  {'id': '309d3ffd-3d06-460d-9427-c559a604d471',...   
13                                                NaN   

                                              catcher  \
0   {'id': '55e1ded0-dbd4-48d2-9df8-f7b92fcd0fef',...   
1   {'id': '3a93bfb5-1fd1-4342-99f1-397161de9d10',...   
2   {'id': 'fc4102d8-b2f6-45f1-9e75-b883838f5bb1',...   
3   {'id': '78b833a2-6813-4529-bf41-21313ebaa4e6',...   
4                                                 NaN   
5                                                 NaN   
6   {'id': '83fe6ab6-d63c-420e-9416-a93d59a9a964',...   
7   {'id': '22ee45d8-0538-4e3e-a758-c515f9b86d11',...   
8   {'id': '9a71201c-c377-45aa-a355-1af6d2c4bae3',...   
9                                                 NaN   
10  {'id': '11864f31-b766-4766-9cbc-5026015ace48',...   
11  {'id': 'b51bb4e5-acdf-423b-abb3-7a1e6694d2c2',...   
12  {'id': '11864f31-b766-4766-9cbc-5026015ace48',...   
13                                                NaN   

                       dismissal-text   r   b  4s  6s      sr     
0              c brian bennett b raza  36  27   4   2  133.33  0  
1                 c raza b muzarabani  66  49   7   3  134.69  0  
2                 c t marumani b raza  10   9   1   0  111.11  0  
3            c madhevere b muzarabani  49  28   4   3  175.00  0  
4                             not out  12   7   2   0  171.43  0  
5                             not out   1   1   0   0  100.00  0  
6      c abhishek sharma b avesh khan   1   2   0   0   50.00  0  
7       c shivam dube b khaleel ahmed  13  10   3   0  130.00  0  
8         c ravi bishnoi b avesh khan   4   5   1   0   80.00  0  
9                             not out  65  49   7   1  132.65  0  
10  c rinku singh b washington sundar  15  16   3   0   93.75  0  
11  c riyan parag b washington sundar   1   2   0   0   50.00  0  
12  c rinku singh b washington sundar  37  26   2   2  142.31  0  
13                            not out  18  10   1   1  180.00  0

In [21]:
df.iloc[0]

batsman           {'id': 'a254feed-0d7c-4f04-a2ab-7bf9ceef156b',...
dismissal                                                     catch
bowler            {'id': '3a93bfb5-1fd1-4342-99f1-397161de9d10',...
catcher           {'id': '55e1ded0-dbd4-48d2-9df8-f7b92fcd0fef',...
dismissal-text                               c brian bennett b raza
r                                                                36
b                                                                27
4s                                                                4
6s                                                                2
sr                                                           133.33
                                                                  0
name                                               Yashasvi Jaiswal
Name: 0, dtype: object

In [17]:
df.iloc[0,0]['name']

'Yashasvi Jaiswal'

In [25]:
df['name'] = df['batsman'].apply(lambda x: x['name']) #fetching the name using lambda function

In [26]:
df

batsman dismissal  \
0   {'id': 'a254feed-0d7c-4f04-a2ab-7bf9ceef156b',...     catch   
1   {'id': '7263e990-a9e9-4829-8adf-760d18d1315c',...     catch   
2   {'id': '83fe6ab6-d63c-420e-9416-a93d59a9a964',...     catch   
3   {'id': '50b70c71-1535-41c0-87fd-c12883105ede',...     catch   
4   {'id': '35ed1b20-38f3-4013-be2e-dc28ffbecfd6',...       NaN   
5   {'id': '11864f31-b766-4766-9cbc-5026015ace48',...       NaN   
6   {'id': '78b833a2-6813-4529-bf41-21313ebaa4e6',...     catch   
7   {'id': 'fc4102d8-b2f6-45f1-9e75-b883838f5bb1',...     catch   
8   {'id': '55e1ded0-dbd4-48d2-9df8-f7b92fcd0fef',...     catch   
9   {'id': '79eee646-64b8-4392-9ad1-cb1c7630034d',...       NaN   
10  {'id': '3a93bfb5-1fd1-4342-99f1-397161de9d10',...     catch   
11  {'id': '79adea1e-ac28-43d7-a734-b05344779200',...     catch   
12  {'id': '0528d8b0-a6ce-498f-a573-d0edb1efcf9b',...     catch   
13  {'id': '397bf103-6977-4e5b-b437-6f448764b36a',...       NaN   

                                               bowler  \
0   {'id': '3a93bfb5-1fd1-4342-99f1-397161de9d10',...   
1   {'id': '50e38c9d-bf39-44b8-b5e6-0c9f36b8cbdf',...   
2   {'id': '3a93bfb5-1fd1-4342-99f1-397161de9d10',...   
3   {'id': '50e38c9d-bf39-44b8-b5e6-0c9f36b8cbdf',...   
4                                                 NaN   
5                                                 NaN   
6   {'id': '332200ad-d1f8-4035-95c5-b33bd1c9a939',...   
7   {'id': '8df6183b-1c95-46d2-85c0-e185792d03f1',...   
8   {'id': '332200ad-d1f8-4035-95c5-b33bd1c9a939',...   
9                                                 NaN   
10  {'id': '309d3ffd-3d06-460d-9427-c559a604d471',...   
11  {'id': '309d3ffd-3d06-460d-9427-c559a604d471',...   
12  {'id': '309d3ffd-3d06-460d-9427-c559a604d471',...   
13                                                NaN   

                                              catcher  \
0   {'id': '55e1ded0-dbd4-48d2-9df8-f7b92fcd0fef',...   
1   {'id': '3a93bfb5-1fd1-4342-99f1-397161de9d10',...   
2   {'id': 'fc4102d8-b2f6-45f1-9e75-b883838f5bb1',...   
3   {'id': '78b833a2-6813-4529-bf41-21313ebaa4e6',...   
4                                                 NaN   
5                                                 NaN   
6   {'id': '83fe6ab6-d63c-420e-9416-a93d59a9a964',...   
7   {'id': '22ee45d8-0538-4e3e-a758-c515f9b86d11',...   
8   {'id': '9a71201c-c377-45aa-a355-1af6d2c4bae3',...   
9                                                 NaN   
10  {'id': '11864f31-b766-4766-9cbc-5026015ace48',...   
11  {'id': 'b51bb4e5-acdf-423b-abb3-7a1e6694d2c2',...   
12  {'id': '11864f31-b766-4766-9cbc-5026015ace48',...   
13                                                NaN   

                       dismissal-text   r   b  4s  6s      sr     \
0              c brian bennett b raza  36  27   4   2  133.33  0   
1                 c raza b muzarabani  66  49   7   3  134.69  0   
2                 c t marumani b raza  10   9   1   0  111.11  0   
3            c madhevere b muzarabani  49  28   4   3  175.00  0   
4                             not out  12   7   2   0  171.43  0   
5                             not out   1   1   0   0  100.00  0   
6      c abhishek sharma b avesh khan   1   2   0   0   50.00  0   
7       c shivam dube b khaleel ahmed  13  10   3   0  130.00  0   
8         c ravi bishnoi b avesh khan   4   5   1   0   80.00  0   
9                             not out  65  49   7   1  132.65  0   
10  c rinku singh b washington sundar  15  16   3   0   93.75  0   
11  c riyan parag b washington sundar   1   2   0   0   50.00  0   
12  c rinku singh b washington sundar  37  26   2   2  142.31  0   
13                            not out  18  10   1   1  180.00  0   

                    name  
0       Yashasvi Jaiswal  
1           Shubman Gill  
2        Abhishek Sharma  
3        Ruturaj Gaikwad  
4           Sanju Samson  
5            Rinku Singh  
6       Wessly Madhevere  
7   Tadiwanashe Marumani  
8         Brian Bennett   
9             Dion Myers  
10        

In [1]:
import seaborn as sns

In [2]:
df = sns.load_dataset("iris")

In [3]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
df.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
df.species.value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [6]:
group = df.species.unique()

In [9]:
group[0]

'setosa'

In [8]:
import pandas as pd

In [10]:
data = {}
for i in group:
    data[i] = df["sepal_length"][df["species"]==i]

In [16]:
data.keys()

dict_keys(['setosa', 'versicolor', 'virginica'])

In [13]:
data['setosa']

0     5.1
1     4.9
2     4.7
3     4.6
4     5.0
5     5.4
6     4.6
7     5.0
8     4.4
9     4.9
10    5.4
11    4.8
12    4.8
13    4.3
14    5.8
15    5.7
16    5.4
17    5.1
18    5.7
19    5.1
20    5.4
21    5.1
22    4.6
23    5.1
24    4.8
25    5.0
26    5.0
27    5.2
28    5.2
29    4.7
30    4.8
31    5.4
32    5.2
33    5.5
34    4.9
35    5.0
36    5.5
37    4.9
38    4.4
39    5.1
40    5.0
41    4.5
42    4.4
43    5.0
44    5.1
45    4.8
46    5.1
47    4.6
48    5.3
49    5.0
Name: sepal_length, dtype: float64

In [14]:
from scipy import stats

In [17]:
f_value , p_value = stats.f_oneway(data["setosa"],data["virginica"])

In [18]:
if p_value < 0.75:
    print ("H0 reject null hypothesis, Ha accepts alternate hypothesis, no connection of the data")
else:
    print ("H0 accept null hypothesis, Ha rejects alternate hypothesis, connection present in the data")

H0 reject null hypothesis, Ha accepts alternate hypothesis, no connection of the data


In [22]:
df1 = pd.read_csv("/Users/saro/Desktop/numpy_pandas/Wine_Quality_Data.csv")

In [20]:
df_wine

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
6492                 24.0                  92.0  0.99114  3.27       0.50   
6493                 57.0                 168.0  0.99490  3.15       0.46   
6494                 30.0                 111.0  0.99254  2.99       0.46   
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  color  
0         9.4        5    red  
1         9.8        5    red  
2         9.8        5    red  
3         9.8        6    red  
4         9.4        5    red  
...       ...      ...    ...  
6492     11.2        6  white  
6493      9.6        5  white  
6494      9.4        6  white  
6495     12.8        7  white  
6496     11.8        6  white  

[6497 rows x 13 columns]

In [23]:
group = df1.quality.unique()
group

array([5, 6, 7, 4, 8, 3, 9])

In [24]:
group = df1.quality.unique()

data1 = {}
for i in group:
  data1[i]=df1["sulphates"][df1["quality"]==i]


f_value , p_value = stats.f_oneway(data1[3],data1[4],data1[5],data1[6],data1[7],data1[8],data1[9])
if p_value<0.075:
  print("H0 Reject null hypothesis, Ha accepts alternate hypothesis , no connection of the data")
else:
  print("H0 accept null hypothesis, Ha rejects alternate hypothesis, connection present in the data")

H0 Reject null hypothesis, Ha accepts alternate hypothesis , no connection of the data


In [25]:
df2 = pd.read_csv("/Users/saro/Desktop/numpy_pandas/Electric_Vehicle_Population_Data.csv")

In [26]:
df2

VIN (1-10)        County       City State  Postal Code  Model Year  \
0       5YJSA1E22K          King    Seattle    WA      98112.0        2019   
1       3MW39FS05R        Yakima     Zillah    WA      98953.0        2024   
2       1N4AZ0CP0F          King       Kent    WA      98031.0        2015   
3       5YJSA1H20F     Snohomish    Bothell    WA      98012.0        2015   
4       JTMAB3FV1N        Yakima     Yakima    WA      98908.0        2022   
...            ...           ...        ...   ...          ...         ...   
191402  5YJ3E1EA0K        Pierce     Sumner    WA      98390.0        2019   
191403  JN1BF0BA7P        Pierce   Wilkeson    WA      98396.0        2023   
191404  7SAYGDEE4R          King  Fall City    WA      98024.0        2024   
191405  7SAXCBE65N  Grays Harbor   Aberdeen    WA      98520.0        2022   
191406  7SAYGAEEXP        Benton   Richland    WA      99352.0        2023   

          Make       Model                   Electric Vehicle Type  \
0        TESLA     MODEL S          Battery Electric Vehicle (BEV)   
1          BMW        330E  Plug-in Hybrid Electric Vehicle (PHEV)   
2       NISSAN        LEAF          Battery Electric Vehicle (BEV)   
3        TESLA     MODEL S          Battery Electric Vehicle (BEV)   
4       TOYOTA  RAV4 PRIME  Plug-in Hybrid Electric Vehicle (PHEV)   
...        ...         ...                                     ...   
191402   TESLA     MODEL 3          Battery Electric Vehicle (BEV)   
191403  NISSAN       ARIYA          Battery Electric Vehicle (BEV)   
191404   TESLA     MODEL Y          Battery Electric Vehicle (BEV)   
191405   TESLA     MODEL X          Battery Electric Vehicle (BEV)   
191406   TESLA     MODEL Y          Battery Electric Vehicle (BEV)   

        Clean Alternative Fuel Vehicle (CAFV) Eligibility  Electric Range  \
0                 Clean Alternative Fuel Vehicle Eligible             270   
1                   Not eligible due to low battery range              20   
2                 Clean Alternative Fuel Vehicle Eligible              84   
3                 Clean Alternative Fuel Vehicle Eligible             208   
4                 Clean Alternative Fuel Vehicle Eligible              42   
...                                                   ...             ...   
191402            Clean Alternative Fuel Vehicle Eligible             220   
191403  Eligibility unknown as battery range has not b...               0   
191404  Eligibility unknown as battery range has not b...               0   
191405  Eligibility unknown as battery range has not b...               0   
191406  Eligibility unknown as battery range has not b...               0   

        Base MSRP  Legislative District  DOL Vehicle ID  \
0               0                  43.0       202233958   
1               0                  15.0       264425178   
2               0                  11.0       114962025   
3               0                   1.0       232724670   
4               0                  14.0       221023589   
...           ...                   ...             ...   
191402          0                  31.0       314927896   
191403          0                  31.0       236213120   
191404          0                   5.0       261335896   
191405          0                  19.0       219273491   
191406          0                   8.0       233761440   

                       Vehicle Location  \
0         POINT (-122.300312 47.629782)   
1       POINT (-120.2658133 46.4063477)   
2         POINT (-122.201564 47.402358)   
3         POINT (-122.206146 47.839957)   
4         POINT (-120.611068 46.596645)   
...                                 ...   
191402  POINT (-122.2337855 47.2055969)   
191403  POINT (-122.0478543 47.1075591)   
191404    POINT (-121.903093 47.567116)   
191405    POINT (-123.807422 46.978243)   
191406  POINT (-119.2958528 46.2421419)   

                                         Electric Utility  2020 Census Tract  
